/**
 * AIOS Agent Executor - Simulates agents progressively working on tasks
 *
 * When the orchestrator creates tasks, this module:
 * 1. Picks up pending tasks in dependency order
 * 2. Assigns them to the right agent type
 * 3. Progressively updates task status (pending → in_progress → completed)
 * 4. Creates agent messages (discussion, status, results)
 * 5. Generates code files based on task type
 * 6. Creates knowledge graph nodes for generated code
 */

import { db } from '@/lib/db'
import { chatCompletion, type ChatMessage } from '@/lib/providers'

// ─── Types ────────────────────────────────────────────────────────────────────

interface ExecutorResult {
  success: boolean
  tasksProcessed: number
  filesCreated: number
  messagesCreated: number
  error?: string
}

// ─── Agent task type mapping ──────────────────────────────────────────────────

const AGENT_TYPE_NAMES: Record<string, string> = {
  planning: 'Code Architect',
  developer: 'Backend Developer',
  frontend: 'Frontend Developer',
  debugger: 'QA Engineer',
  document: 'Documentation Writer',
  security: 'Security Analyst',
  research: 'Code Architect',
}

// ─── Code templates for different task types ──────────────────────────────────

function generateCodeForTask(
  task: { title: string; description?: string | null; type?: string | null },
  project: { name: string; techStack?: string | null; category?: string | null }
): { path: string; content: string; language: string }[] {
  const files: { path: string; content: string; language: string }[] = []
  const taskType = task.type || 'development'
  const taskTitle = task.title.toLowerCase()
  const projectName = project.name.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()

  if (taskType === 'development' || taskType === 'analysis') {
    // Backend / API files
    if (taskTitle.includes('api') || taskTitle.includes('backend') || taskTitle.includes('server')) {
      files.push({
        path: `src/app/api/${projectName}/route.ts`,
        content: `import { NextRequest, NextResponse } from 'next/server'\n\n/**\n * ${task.title}\n * Auto-generated by AIOS Agent\n */\nexport async function GET(request: NextRequest) {\n  try {\n    // TODO: Implement GET handler\n    return NextResponse.json({ success: true, data: [] })\n  } catch (error) {\n    console.error('GET error:', error)\n    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })\n  }\n}\n\nexport async function POST(request: NextRequest) {\n  try {\n    const body = await request.json()\n    // TODO: Implement POST handler\n    return NextResponse.json({ success: true, data: body }, { status: 201 })\n  } catch (error) {\n    console.error('POST error:', error)\n    return NextResponse.json({ error: 'Internal server error' }, { status: 500 })\n  }\n}\n`,
        language: 'typescript',
      })
    }

    if (taskTitle.includes('model') || taskTitle.includes('schema') || taskTitle.includes('database')) {
      files.push({
        path: `prisma/schema-extension.prisma`,
        content: `// ${task.title}\n// Auto-generated by AIOS Agent\n// Add your custom models here\n\n// model Example {\n//   id        String   @id @default(cuid())\n//   name      String\n//   createdAt DateTime @default(now())\n//   updatedAt DateTime @updatedAt\n// }\n`,
        language: 'prisma',
      })
    }

    if (taskTitle.includes('component') || taskTitle.includes('frontend') || taskTitle.includes('ui') || taskTitle.includes('page')) {
      const componentName = task.title.replace(/[^a-zA-Z0-9]/g, '')
      files.push({
        path: `src/components/${componentName}.tsx`,
        content: `'use client'\n\nimport { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'\n\n/**\n * ${task.title}\n * Auto-generated by AIOS Agent\n */\nexport default function ${componentName}() {\n  return (\n    <Card>\n      <CardHeader>\n        <CardTitle>${task.title}</CardTitle>\n      </CardHeader>\n      <CardContent>\n        <p className="text-muted-foreground">Component content for ${task.title}</p>\n      </CardContent>\n    </Card>\n  )\n}\n`,
        language: 'typescript',
      })
    }

    // If no specific match, create a general utility file
    if (files.length === 0) {
      const slug = task.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()
      files.push({
        path: `src/lib/${slug}.ts`,
        content: `/**\n * ${task.title}\n * Auto-generated by AIOS Agent\n * ${task.description || ''}\n */\n\nexport interface Config {\n  // Add configuration properties\n}\n\nexport async function execute(config: Config) {\n  // TODO: Implement ${task.title}\n  console.log('Executing:', '${task.title}')\n  return { success: true }\n}\n`,
        language: 'typescript',
      })
    }
  }

  if (taskType === 'documentation') {
    files.push({
      path: `docs/${projectName}-guide.md`,
      content: `# ${project.name}\n\n## ${task.title}\n\n${task.description || 'Documentation section'}\n\n## Installation\n\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Usage\n\n\`\`\`typescript\nimport { execute } from './src/lib/main'\n\nconst result = await execute({})\nconsole.log(result)\n\`\`\`\n\n## API Reference\n\nSee the generated API documentation for details.\n`,
      language: 'markdown',
    })
  }

  if (taskType === 'testing') {
    const slug = task.title.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase()
    files.push({
      path: `tests/${slug}.test.ts`,
      content: `import { describe, it, expect } from 'vitest'\n\n/**\n * ${task.title}\n * Auto-generated by AIOS QA Agent\n */\ndescribe('${task.title}', () => {\n  it('should execute successfully', async () => {\n    // TODO: Implement test\n    expect(true).toBe(true)\n  })\n\n  it('should handle errors gracefully', async () => {\n    // TODO: Implement error test\n    expect(() => {}).not.toThrow()\n  })\n\n  it('should validate input', async () => {\n    // TODO: Implement validation test\n    expect(true).toBe(true)\n  })\n})\n`,
      language: 'typescript',
    })
  }

  if (taskType === 'security') {
    files.push({
      path: `docs/security-audit.md`,
      content: `# Security Audit Report\n\n## ${task.title}\n\n### Findings\n\n| Severity | Finding | Status |\n|----------|---------|--------|\n| Info | Input validation recommended | Open |\n| Info | Rate limiting recommended | Open |\n\n### Recommendations\n\n1. Implement input validation on all API endpoints\n2. Add rate limiting to prevent abuse\n3. Use environment variables for secrets\n4. Enable CORS with specific origins only\n5. Add authentication middleware\n\n### Next Steps\n\n- [ ] Review authentication implementation\n- [ ] Test input validation\n- [ ] Configure rate limiting\n`,
      language: 'markdown',
    })
  }

  return files
}

// ─── Main executor ────────────────────────────────────────────────────────────

export async function executeAgentTasks(projectId: string): Promise<ExecutorResult> {
  const result: ExecutorResult = {
    success: true,
    tasksProcessed: 0,
    filesCreated: 0,
    messagesCreated: 0,
  }

  try {
    // Get project with pending/in_progress tasks
    const project = await db.project.findUnique({
      where: { id: projectId },
      include: {
        tasks: {
          orderBy: { createdAt: 'asc' },
        },
      },
    })

    if (!project) {
      return { ...result, success: false, error: 'Project not found' }
    }

    // Find the next task to execute (pending or in_progress, in order)
    const pendingTask = project.tasks.find(t => t.status === 'pending')
    const inProgressTask = project.tasks.find(t => t.status === 'in_progress')

    // If there's a task in progress, complete it
    if (inProgressTask) {
      await completeTask(projectId, inProgressTask, project)
      result.tasksProcessed++
      result.filesCreated++
      result.messagesCreated += 2
      return result
    }

    // If there's a pending task, start it
    if (pendingTask) {
      await startTask(projectId, pendingTask, project)
      result.tasksProcessed++
      return result
    }

    // No more tasks - check if all are completed
    const allDone = project.tasks.length > 0 && project.tasks.every(t => t.status === 'completed')
    if (allDone && project.orchestratorStatus === 'running') {
      await db.project.update({
        where: { id: projectId },
        data: {
          orchestratorStatus: 'completed',
          status: 'completed',
          completedAt: new Date(),
        },
      })

      await db.agentMessage.create({
        data: {
          projectId,
          fromRole: 'system',
          toRole: 'all',
          type: 'status',
          content: `## 🎉 All Tasks Completed!\n\nAll ${project.tasks.length} tasks for "${project.name}" have been completed successfully. The project is now marked as completed.\n\nYou can download the project as ZIP or push it to GitHub.`,
        },
      })
      result.messagesCreated++
    }

    return result
  } catch (error) {
    console.error('Agent executor error:', error)
    return {
      ...result,
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error',
    }
  }
}

// ─── Start a task ─────────────────────────────────────────────────────────────

async function startTask(
  projectId: string,
  task: { id: string; title: string; description?: string | null; type?: string | null; assigneeId?: string | null },
  project: { name: string; techStack?: string | null; category?: string | null; description?: string | null }
) {
  // Update task to in_progress
  await db.task.update({
    where: { id: task.id },
    data: { status: 'in_progress' },
  })

  // Find the assigned agent
  let agentName = 'Agent'
  if (task.assigneeId) {
    const agent = await db.agent.findUnique({ where: { id: task.assigneeId } })
    if (agent) agentName = agent.name || agent.type
  }

  // Create a "started" message
  await db.agentMessage.create({
    data: {
      projectId,
      fromRole: 'agent',
      toRole: 'all',
      type: 'status',
      content: `🔄 **${agentName}** started working on: **${task.title}**\n\n${task.description ? `> ${task.description}\n` : ''}Analyzing requirements and preparing implementation...`,
      fromAgentId: task.assigneeId,
      toAgentId: null,
      taskIds: JSON.stringify([task.id]),
      metadata: JSON.stringify({ taskAction: 'started', taskId: task.id }),
    },
  })

  // Try to use AI to generate a more detailed progress message
  try {
    const messages: ChatMessage[] = [
      {
        role: 'system',
        content: 'You are an AI agent working on a software project. Write a brief progress message (2-3 sentences) about what you are doing for this task. Be technical and specific.',
      },
      {
        role: 'user',
        content: `Project: ${project.name} (${project.category || 'Web App'})\nTask: ${task.title}\nDescription: ${task.description || 'N/A'}\nTech Stack: ${project.techStack || 'Not specified'}`,
      },
    ]

    const completion = await chatCompletion({ messages, temperature: 0.7, maxTokens: 200 })
    
    await db.agentMessage.create({
      data: {
        projectId,
        fromRole: 'agent',
        toRole: 'all',
        type: 'discussion',
        content: completion.content,
        fromAgentId: task.assigneeId,
        toAgentId: null,
        taskIds: JSON.stringify([task.id]),
        metadata: JSON.stringify({ taskAction: 'progress', taskId: task.id }),
      },
    })
  } catch {
    // AI not available - that's fine, we already created the status message
  }
}

// ─── Complete a task ──────────────────────────────────────────────────────────

async function completeTask(
  projectId: string,
  task: { id: string; title: string; description?: string | null; type?: string | null; assigneeId?: string | null },
  project: { name: string; techStack?: string | null; category?: string | null; description?: string | null }
) {
  // Update task to completed
  await db.task.update({
    where: { id: task.id },
    data: { status: 'completed' },
  })

  // Find the assigned agent
  let agentName = 'Agent'
  if (task.assigneeId) {
    const agent = await db.agent.findUnique({ where: { id: task.assigneeId } })
    if (agent) agentName = agent.name || agent.type
  }

  // Generate code files for this task
  const generatedFiles = generateCodeForTask(task, project)
  let filesCreated = 0

  for (const file of generatedFiles) {
    try {
      // Check if file already exists
      const existing = await db.projectFile.findFirst({
        where: { projectId, path: file.path },
      })

      if (existing) {
        // Update existing file
        await db.projectFile.update({
          where: { id: existing.id },
          data: {
            content: file.content,
            size: Buffer.byteLength(file.content, 'utf-8'),
            source: 'generated',
            language: file.language,
          },
        })
      } else {
        // Create new file
        await db.projectFile.create({
          data: {
            projectId,
            name: file.path.split('/').pop() || file.path,
            path: file.path,
            content: file.content,
            language: file.language,
            size: Buffer.byteLength(file.content, 'utf-8'),
            source: 'generated',
            isDirectory: false,
          },
        })
      }
      filesCreated++
    } catch (fileError) {
      console.error(`Failed to create file ${file.path}:`, fileError)
    }
  }

  // Create a "completed" message
  const fileList = generatedFiles.map(f => `- \`${f.path}\` (${f.language})`).join('\n')
  await db.agentMessage.create({
    data: {
      projectId,
      fromRole: 'agent',
      toRole: 'all',
      type: 'result',
      content: `✅ **${agentName}** completed: **${task.title}**\n\n${filesCreated > 0 ? `**Files generated:**\n${fileList}` : 'Task completed successfully.'}\n\n${task.description ? `> ${task.description}` : ''}`,
      fromAgentId: task.assigneeId,
      toAgentId: null,
      taskIds: JSON.stringify([task.id]),
      metadata: JSON.stringify({ taskAction: 'completed', taskId: task.id, filesCreated }),
    },
  })

  // Create knowledge graph nodes for generated files
  for (const file of generatedFiles) {
    try {
      await db.knowledgeNode.create({
        data: {
          projectId,
          type: 'file',
          name: file.path.split('/').pop() || file.path,
          path: file.path,
          description: `Generated by ${agentName} for: ${task.title}`,
          language: file.language,
          linesOfCode: file.content.split('\n').length,
          importance: 0.7,
          metadata: JSON.stringify({ source: 'agent-generated', taskId: task.id }),
        },
      })
    } catch {
      // Knowledge graph creation failure is non-critical
    }
  }
}

// ─── Batch execute (for API route) ───────────────────────────────────────────

export async function getProjectExecutionStatus(projectId: string) {
  const project = await db.project.findUnique({
    where: { id: projectId },
    include: {
      tasks: {
        select: {
          id: true,
          title: true,
          status: true,
          type: true,
          priority: true,
          assigneeId: true,
        },
        orderBy: { createdAt: 'asc' },
      },
    },
  })

  if (!project) return null

  const pending = project.tasks.filter(t => t.status === 'pending').length
  const inProgress = project.tasks.filter(t => t.status === 'in_progress').length
  const completed = project.tasks.filter(t => t.status === 'completed').length
  const total = project.tasks.length

  return {
    projectId: project.id,
    projectName: project.name,
    orchestratorStatus: project.orchestratorStatus,
    projectStatus: project.status,
    tasks: {
      total,
      pending,
      inProgress,
      completed,
      progress: total > 0 ? Math.round((completed / total) * 100) : 0,
    },
  }
}
