/**
 * AIOS Orchestrator - Shared orchestration logic
 *
 * This module provides the core orchestration workflow that:
 * 1. Creates default agents if none exist
 * 2. Analyzes project requirements using AI
 * 3. Generates task breakdowns and assigns agents
 * 4. Creates agent messages with instructions
 * 5. Auto-generates documentation after completion
 */

import { db } from '@/lib/db'
import { chatCompletion, type ChatMessage } from '@/lib/providers'

// ─── Types ────────────────────────────────────────────────────────────────────

interface OrchestratorLogEntry {
  timestamp: string
  event: string
  details?: unknown
}

interface ParsedTask {
  title: string
  description: string
  type: string
  priority: string
  assigneeType: string
  dependencies: number[]
}

export interface OrchestrationResult {
  success: boolean
  orchestratorStatus: string
  projectStatus: string
  tasksCreated: number
  messagesCreated: number
  agentsCreated: number
  documentationGenerated: boolean
  error?: string
}

// ─── Default Agents ───────────────────────────────────────────────────────────

const DEFAULT_AGENTS = [
  {
    name: 'Code Architect',
    type: 'planning',
    description: 'Analyzes project requirements, designs system architecture, and creates technical specifications. Responsible for breaking down complex problems into manageable components.',
    avatar: '🏗️',
    capabilities: ['architecture', 'system-design', 'technical-specs', 'code-review'],
  },
  {
    name: 'Frontend Developer',
    type: 'developer',
    description: 'Implements user interfaces, client-side logic, and frontend components. Expert in React, TypeScript, CSS, and responsive design.',
    avatar: '🎨',
    capabilities: ['react', 'typescript', 'css', 'ui-ux', 'responsive-design'],
  },
  {
    name: 'Backend Developer',
    type: 'developer',
    description: 'Builds server-side APIs, database schemas, and backend services. Expert in Node.js, databases, authentication, and API design.',
    avatar: '⚙️',
    capabilities: ['nodejs', 'api-design', 'databases', 'authentication', 'server-logic'],
  },
  {
    name: 'QA Engineer',
    type: 'debugger',
    description: 'Tests application functionality, identifies bugs, and ensures code quality. Responsible for writing test cases and verifying feature completeness.',
    avatar: '🔍',
    capabilities: ['testing', 'bug-detection', 'quality-assurance', 'test-cases', 'regression-testing'],
  },
  {
    name: 'Documentation Writer',
    type: 'document',
    description: 'Creates comprehensive project documentation including README files, API docs, architecture guides, and installation procedures.',
    avatar: '📝',
    capabilities: ['technical-writing', 'readme', 'api-docs', 'architecture-docs', 'tutorials'],
  },
  {
    name: 'Security Analyst',
    type: 'security',
    description: 'Reviews code for security vulnerabilities, ensures best practices for authentication and data protection, and performs security audits.',
    avatar: '🛡️',
    capabilities: ['security-audit', 'vulnerability-scanning', 'authentication', 'data-protection', 'compliance'],
  },
]

// ─── Helper: extract JSON from AI response ────────────────────────────────────

function extractJsonFromResponse(text: string): string {
  const codeBlockMatch = text.match(/```(?:json)?\s*\n?([\s\S]*?)\n?\s*```/)
  if (codeBlockMatch) return codeBlockMatch[1].trim()

  const firstBracket = text.indexOf('[')
  const lastBracket = text.lastIndexOf(']')
  if (firstBracket !== -1 && lastBracket > firstBracket) {
    return text.substring(firstBracket, lastBracket + 1)
  }

  return text.trim()
}

// ─── Task type to agent type mapping ──────────────────────────────────────────

const TASK_TYPE_TO_AGENT: Record<string, string> = {
  development: 'developer',
  testing: 'debugger',
  security: 'security',
  documentation: 'document',
  research: 'research',
  analysis: 'research',
  planning: 'planning',
}

// ─── Ensure default agents exist ──────────────────────────────────────────────

export async function ensureDefaultAgents(): Promise<number> {
  const existingCount = await db.agent.count()

  if (existingCount > 0) {
    return 0 // Agents already exist
  }

  let created = 0
  for (const agentDef of DEFAULT_AGENTS) {
    await db.agent.create({
      data: {
        name: agentDef.name,
        type: agentDef.type,
        description: agentDef.description,
        avatar: agentDef.avatar,
        capabilities: JSON.stringify(agentDef.capabilities),
        isActive: true,
        isDefault: true,
        systemPrompt: `You are ${agentDef.name}, an AI agent specialized in ${agentDef.type}. ${agentDef.description}`,
      },
    })
    created++
  }

  return created
}

// ─── Auto-generate documentation ──────────────────────────────────────────────

async function autoGenerateDocumentation(projectId: string): Promise<boolean> {
  try {
    const project = await db.project.findUnique({
      where: { id: projectId },
      include: {
        projectFiles: {
          select: { name: true, path: true, language: true, size: true, source: true },
          orderBy: { path: 'asc' },
        },
        tasks: {
          select: { title: true, status: true, type: true, priority: true, description: true },
          orderBy: { createdAt: 'asc' },
        },
        graphNodes: {
          select: { name: true, type: true, description: true, path: true, language: true },
          take: 50,
        },
      },
    })

    if (!project) return false

    let techStackDisplay = project.techStack || ''
    if (techStackDisplay) {
      try {
        const parsed = JSON.parse(techStackDisplay)
        if (Array.isArray(parsed)) techStackDisplay = parsed.join(', ')
      } catch { /* keep as-is */ }
    }

    const fileList = project.projectFiles
      .map(f => `  - ${f.path} (${f.language || 'unknown'}, ${f.size} bytes)`)
      .join('\n')

    const taskList = project.tasks
      .map(t => `  - [${t.status}] ${t.title} (${t.type || 'general'}, ${t.priority})`)
      .join('\n')

    const nodeList = project.graphNodes
      .map(n => `  - ${n.name} (${n.type})${n.path ? ` at ${n.path}` : ''}${n.description ? `: ${n.description}` : ''}`)
      .join('\n')

    const systemPrompt = `You are a technical documentation writer. Generate comprehensive project documentation in markdown format.

Generate TWO sections, separated by a special marker:

===README===
Generate a README.md with:
- Project title and description
- Installation instructions (step-by-step, with specific commands)
- Usage guide with examples
- Configuration guide
- API documentation (if applicable)

===DOCUMENTATION===
Generate detailed architecture documentation with:
- Architecture overview
- Component/module descriptions
- Security considerations
- Testing strategy
- Troubleshooting guide

Make it concise, practical, and focused on installation procedures. Use proper markdown formatting.`

    const userMessage = `Generate documentation for this project:

**Project Name:** ${project.name}
**Description:** ${project.description || 'No description provided'}
**Category:** ${project.category || 'General'}
**Tech Stack:** ${techStackDisplay || 'Not specified'}
**Requirements:** ${project.requirements || 'No specific requirements'}

**Project Files (${project.projectFiles.length}):**
${fileList || '  (No files yet)'}

**Tasks (${project.tasks.length}):**
${taskList || '  (No tasks yet)'}

**Knowledge Graph Nodes (${project.graphNodes.length}):**
${nodeList || '  (No knowledge graph data yet)'}

Generate documentation now.`

    const messages: ChatMessage[] = [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMessage },
    ]

    const completion = await chatCompletion({ messages, temperature: 0.5, maxTokens: 4096 })
    const aiResponse = completion.content

    // Split response into README and documentation sections
    let readme = ''
    let documentation = ''

    const separatorIndex = aiResponse.indexOf('===README===')
    const docSeparatorIndex = aiResponse.indexOf('===DOCUMENTATION===')

    if (separatorIndex !== -1 && docSeparatorIndex !== -1) {
      readme = aiResponse
        .substring(separatorIndex + '===README==='.length, docSeparatorIndex)
        .trim()
      documentation = aiResponse
        .substring(docSeparatorIndex + '===DOCUMENTATION==='.length)
        .trim()
    } else {
      documentation = aiResponse
      readme = `# ${project.name}\n\n${project.description || ''}\n\n## Tech Stack\n${techStackDisplay || 'Not specified'}\n\n## Getting Started\nSee the full documentation for installation and usage instructions.\n`
    }

    await db.project.update({
      where: { id: projectId },
      data: { readme, documentation },
    })

    return true
  } catch (error) {
    console.error('Auto-documentation generation failed:', error)
    return false
  }
}

// ─── Main orchestration workflow ──────────────────────────────────────────────

export async function runOrchestration(
  projectId: string,
  options?: { skipDocumentation?: boolean }
): Promise<OrchestrationResult> {
  const log: OrchestratorLogEntry[] = []

  const addLog = (event: string, details?: unknown) => {
    log.push({ timestamp: new Date().toISOString(), event, details })
  }

  try {
    // Step 0: Load project
    const project = await db.project.findUnique({ where: { id: projectId } })
    if (!project) {
      return { success: false, orchestratorStatus: 'failed', projectStatus: 'planning', tasksCreated: 0, messagesCreated: 0, agentsCreated: 0, documentationGenerated: false, error: 'Project not found' }
    }

    // Load existing log
    const existingLog: OrchestratorLogEntry[] = (() => {
      try { return JSON.parse(project.orchestratorLog || '[]') } catch { return [] }
    })()

    addLog('orchestration_started', { projectId })

    // Step 1: Update status to "analyzing"
    addLog('status_changed', { from: project.orchestratorStatus || 'idle', to: 'analyzing' })
    await db.project.update({
      where: { id: projectId },
      data: {
        orchestratorStatus: 'analyzing',
        orchestratorLog: JSON.stringify([...existingLog, ...log]),
      },
    })

    // Step 2: Ensure default agents exist
    const agentsCreated = await ensureDefaultAgents()
    if (agentsCreated > 0) {
      addLog('default_agents_created', { count: agentsCreated, agents: DEFAULT_AGENTS.map(a => a.name) })
    }

    // Step 3: Use AI to analyze project requirements and generate task breakdown
    let techStackDisplay = project.techStack || ''
    if (techStackDisplay) {
      try {
        const parsed = JSON.parse(techStackDisplay)
        if (Array.isArray(parsed)) techStackDisplay = parsed.join(', ')
      } catch { /* keep as-is */ }
    }

    const systemPrompt = `You are the AIOS Orchestrator. Analyze this project and create a detailed task breakdown.

Generate a JSON array of tasks, each with:
- title: string
- description: string (detailed instructions for the agent)
- type: "development" | "research" | "analysis" | "documentation" | "security" | "testing"
- priority: "low" | "medium" | "high" | "critical"
- assigneeType: agent type that should handle this (developer, debugger, security, document, research, planning)
- dependencies: array of task indices this depends on (0-based)

Generate at least 5-10 tasks covering all aspects of the project.
Return ONLY the JSON array, no markdown, no explanation.`

    const userMessage = `Project: ${project.name}
Description: ${project.description || 'No description provided'}
Category: ${project.category || 'Not specified'}
Tech Stack: ${techStackDisplay || 'Not specified'}
Requirements: ${project.requirements || 'No specific requirements'}`

    const messages: ChatMessage[] = [
      { role: 'system', content: systemPrompt },
      { role: 'user', content: userMessage },
    ]

    let aiResponse: string
    try {
      const completion = await chatCompletion({ messages, temperature: 0.7 })
      aiResponse = completion.content
    } catch (aiError) {
      const errorMsg = aiError instanceof Error ? aiError.message : 'AI analysis failed'
      addLog('ai_analysis_failed', { error: errorMsg })
      await db.project.update({
        where: { id: projectId },
        data: {
          orchestratorStatus: 'failed',
          orchestratorLog: JSON.stringify([...existingLog, ...log]),
        },
      })
      return { success: false, orchestratorStatus: 'failed', projectStatus: project.status, tasksCreated: 0, messagesCreated: 0, agentsCreated: 0, documentationGenerated: false, error: `AI analysis failed: ${errorMsg}` }
    }

    addLog('analysis_completed', { responseLength: aiResponse.length })

    // Step 4: Parse AI response into task definitions
    let parsedTasks: ParsedTask[]
    try {
      const jsonStr = extractJsonFromResponse(aiResponse)
      parsedTasks = JSON.parse(jsonStr)
      if (!Array.isArray(parsedTasks)) throw new Error('Response is not a JSON array')
    } catch (parseError) {
      addLog('parse_failed', { error: parseError instanceof Error ? parseError.message : 'Parse error' })
      await db.project.update({
        where: { id: projectId },
        data: {
          orchestratorStatus: 'failed',
          orchestratorLog: JSON.stringify([...existingLog, ...log]),
        },
      })
      return { success: false, orchestratorStatus: 'failed', projectStatus: project.status, tasksCreated: 0, messagesCreated: 0, agentsCreated: 0, documentationGenerated: false, error: 'Failed to parse orchestrator task breakdown' }
    }

    // Step 5: Update status to "assigning"
    addLog('status_changed', { from: 'analyzing', to: 'assigning' })
    await db.project.update({
      where: { id: projectId },
      data: {
        orchestratorStatus: 'assigning',
        orchestratorLog: JSON.stringify([...existingLog, ...log]),
      },
    })

    // Step 6: Find or create agent cache for assignment
    const agentCache: Record<string, string | null> = {}
    async function getAgentId(type: string): Promise<string | null> {
      if (agentCache[type] !== undefined) return agentCache[type]
      const agent = await db.agent.findFirst({ where: { type, isActive: true } })
      agentCache[type] = agent?.id || null
      return agentCache[type]
    }

    // Step 7: Create tasks
    const createdTasks = []
    const taskIdMap: Record<number, string> = {}

    for (let i = 0; i < parsedTasks.length; i++) {
      const taskDef = parsedTasks[i]
      const assigneeType = taskDef.assigneeType || TASK_TYPE_TO_AGENT[taskDef.type] || 'developer'
      const assigneeId = await getAgentId(assigneeType)

      const task = await db.task.create({
        data: {
          title: taskDef.title || `Task ${i + 1}`,
          description: taskDef.description || null,
          status: 'pending',
          priority: taskDef.priority || 'medium',
          type: taskDef.type || 'development',
          projectId,
          creatorId: project.userId,
          assigneeId,
          metadata: JSON.stringify({
            source: 'orchestrator',
            assigneeType,
            dependencies: taskDef.dependencies || [],
            generatedAt: new Date().toISOString(),
            taskIndex: i,
          }),
        },
      })

      taskIdMap[i] = task.id
      createdTasks.push(task)
    }

    addLog('tasks_created', { count: createdTasks.length, taskTitles: createdTasks.map(t => t.title) })

    // Step 8: Create AgentMessage records for each task instruction
    const agentMessages = []
    for (let i = 0; i < createdTasks.length; i++) {
      const task = createdTasks[i]
      const taskDef = parsedTasks[i]
      const assigneeType = taskDef.assigneeType || TASK_TYPE_TO_AGENT[taskDef.type] || 'developer'
      const assigneeId = await getAgentId(assigneeType)

      const depTasks = (taskDef.dependencies || [])
        .map((depIdx: number) => taskIdMap[depIdx])
        .filter(Boolean)

      const instructionContent = `## Task Assignment: ${task.title}

**Type:** ${task.type}
**Priority:** ${task.priority}

### Instructions:
${taskDef.description || 'Complete this task according to project requirements.'}

${depTasks.length > 0 ? `### Dependencies:\nThis task depends on: ${depTasks.map(tid => `Task ${tid}`).join(', ')}` : '### Dependencies:\nNo dependencies — this task can start immediately.'}

### Project Context:
- Project: ${project.name}
- Category: ${project.category || 'General'}
- Tech Stack: ${techStackDisplay || 'Not specified'}

Please proceed with this task and report results when complete.`

      const agentMessage = await db.agentMessage.create({
        data: {
          projectId,
          fromRole: 'orchestrator',
          toRole: 'agent',
          type: 'instruction',
          content: instructionContent,
          fromAgentId: null, // orchestrator is not a specific agent
          toAgentId: assigneeId,
          taskIds: JSON.stringify([task.id]),
          metadata: JSON.stringify({ taskIndex: i, assigneeType }),
        },
      })

      agentMessages.push(agentMessage)
    }

    addLog('agent_messages_created', { count: agentMessages.length })

    // Step 9: Create a broadcast summary message
    const summaryContent = `## Orchestration Complete for: ${project.name}

The orchestrator has analyzed the project and created ${createdTasks.length} tasks assigned across multiple agents.

### Task Summary:
${createdTasks.map((t, i) => `${i + 1}. **${t.title}** (${t.type}, ${t.priority} priority)`).join('\n')}

### Agent Assignments:
${Object.entries(agentCache).filter(([, id]) => id !== null).map(([type]) => `- ${type}`).join('\n')}

All agents should review their assigned tasks and begin execution according to dependency order.`

    await db.agentMessage.create({
      data: {
        projectId,
        fromRole: 'orchestrator',
        toRole: 'all',
        type: 'status',
        content: summaryContent,
        fromAgentId: null,
        toAgentId: null,
        taskIds: JSON.stringify(createdTasks.map(t => t.id)),
        metadata: JSON.stringify({ orchestratorBroadcast: true }),
      },
    })

    addLog('broadcast_summary_sent')

    // Step 10: Update project status to "running"
    addLog('status_changed', { orchestratorStatus: 'running', projectStatus: 'in_progress' })
    await db.project.update({
      where: { id: projectId },
      data: {
        orchestratorStatus: 'running',
        status: 'in_progress',
        startedAt: project.startedAt || new Date(),
        orchestratorLog: JSON.stringify([...existingLog, ...log]),
      },
    })

    // Step 11: Keep orchestrator as "running" - agents will execute tasks progressively
    // The agent executor (called by the frontend polling) will process tasks one by one
    // and mark the orchestrator as "completed" only when all tasks are done.
    addLog('agents_execution_started', {
      tasksCreated: createdTasks.length,
      messagesCreated: agentMessages.length + 1,
      agentsCreated,
      note: 'Agents will execute tasks progressively via /api/projects/[id]/execute',
    })

    // Update log with running status
    await db.project.update({
      where: { id: projectId },
      data: {
        orchestratorStatus: 'running',
        status: 'in_progress',
        orchestratorLog: JSON.stringify([...existingLog, ...log]),
      },
    })

    // Auto-generate documentation in the background (non-blocking)
    if (!options?.skipDocumentation) {
      autoGenerateDocumentation(projectId).catch((docError) => {
        console.error('Auto-documentation failed:', docError)
      })
    }

    return {
      success: true,
      orchestratorStatus: 'running',
      projectStatus: 'in_progress',
      tasksCreated: createdTasks.length,
      messagesCreated: agentMessages.length + 1,
      agentsCreated,
      documentationGenerated: false,
    }
  } catch (error) {
    console.error('Orchestration error:', error)
    const errorMsg = error instanceof Error ? error.message : 'Unknown error'

    // Try to update the project status to failed
    try {
      const project = await db.project.findUnique({ where: { id: projectId } })
      if (project) {
        const existingLog: OrchestratorLogEntry[] = (() => {
          try { return JSON.parse(project.orchestratorLog || '[]') } catch { return [] }
        })()
        log.push({ timestamp: new Date().toISOString(), event: 'orchestration_failed', details: { error: errorMsg } })
        await db.project.update({
          where: { id: projectId },
          data: {
            orchestratorStatus: 'failed',
            orchestratorLog: JSON.stringify([...existingLog, ...log]),
          },
        })
      }
    } catch {
      // Can't update status, but don't mask original error
    }

    return {
      success: false,
      orchestratorStatus: 'failed',
      projectStatus: 'planning',
      tasksCreated: 0,
      messagesCreated: 0,
      agentsCreated: 0,
      documentationGenerated: false,
      error: errorMsg,
    }
  }
}
