import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { ZipArchive } from 'archiver'
import { Readable } from 'stream'

interface GeneratedFile {
  path: string
  content: string
}

/**
 * Generate project files based on project category, tech stack, and requirements
 * (Same logic as /api/github/push/route.ts)
 */
function generateProjectFiles(project: {
  name: string
  description: string | null
  category: string | null
  techStack: string | null
  requirements: string | null
  notes: string | null
}): GeneratedFile[] {
  const files: GeneratedFile[] = []
  const techList: string[] = project.techStack ? JSON.parse(project.techStack) : []
  const techLower = techList.map(t => t.toLowerCase())

  // README.md
  const readme = `# ${project.name}

${project.description || 'A project built with AIOS.'}

## About

${project.requirements ? `### Requirements\n${project.requirements}\n` : ''}
${project.notes ? `### Notes\n${project.notes}\n` : ''}

## Tech Stack

${techList.length > 0 ? techList.map(t => `- ${t}`).join('\n') : '- Not specified'}

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Run development server
npm run dev
\`\`\`

## Project Structure

\`\`\`
src/
├── app/          # Application routes and pages
├── components/   # Reusable UI components
├── lib/          # Utility functions and helpers
└── types/        # TypeScript type definitions
\`\`\`

---

*Generated by [AIOS](https://github.com/ai-os) - AI Operating System*
`
  files.push({ path: 'README.md', content: readme })

  // .gitignore
  const gitignore = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Next.js
.next/
out/

# Production
build/
dist/

# Misc
.DS_Store
*.pem
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Vercel
.vercel

# TypeScript
*.tsbuildinfo
next-env.d.ts
`
  files.push({ path: '.gitignore', content: gitignore })

  // package.json
  const isWebProject = ['web_app', 'api', 'automation', 'mobile', 'desktop'].includes(project.category || '')
  const isAIProject = project.category === 'ai' || techLower.some(t => t.includes('ai') || t.includes('ml') || t.includes('tensor'))

  if (isWebProject || isAIProject || techLower.some(t => ['javascript', 'typescript', 'react', 'next.js', 'node', 'node.js', 'vue', 'angular'].includes(t))) {
    const isNextJs = techLower.some(t => t.includes('next'))
    const isReact = techLower.some(t => t.includes('react'))
    const isVue = techLower.some(t => t.includes('vue'))

    const packageJson = {
      name: project.name.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      version: '0.1.0',
      description: project.description || `AIOS project: ${project.name}`,
      private: true,
      scripts: isNextJs
        ? { dev: 'next dev', build: 'next build', start: 'next start', lint: 'next lint' }
        : isReact
          ? { dev: 'react-scripts start', build: 'react-scripts build', test: 'react-scripts test', eject: 'react-scripts eject' }
          : isVue
            ? { dev: 'vue-cli-service serve', build: 'vue-cli-service build', lint: 'vue-cli-service lint' }
            : { dev: 'node src/index.js', build: 'tsc', start: 'node dist/index.js' },
      dependencies: {},
      devDependencies: {},
    }
    files.push({ path: 'package.json', content: JSON.stringify(packageJson, null, 2) })

    // tsconfig.json
    if (isNextJs || techLower.some(t => t.includes('typescript'))) {
      const tsconfig = {
        compilerOptions: {
          target: 'es5',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          ...(isNextJs ? { plugins: [{ name: 'next' }] } : {}),
          paths: { '@/*': ['./src/*'] },
        },
        include: ['src', ...(isNextJs ? ['.next/types/**/*.ts'] : [])],
        exclude: ['node_modules'],
      }
      files.push({ path: 'tsconfig.json', content: JSON.stringify(tsconfig, null, 2) })
    }

    // src/ structure
    if (isNextJs) {
      files.push({
        path: 'src/app/page.tsx',
        content: `export default function Home() {
  return (
    <main>
      <h1>${project.name}</h1>
      <p>${project.description || 'Welcome to the project.'}</p>
    </main>
  )
}
`,
      })
      files.push({
        path: 'src/app/layout.tsx',
        content: `import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '${project.name}',
  description: '${project.description || ''}',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
      })
      files.push({
        path: 'src/app/globals.css',
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
      })
    } else if (isReact) {
      files.push({
        path: 'src/App.tsx',
        content: `import React from 'react'

function App() {
  return (
    <div>
      <h1>${project.name}</h1>
      <p>${project.description || 'Welcome to the project.'}</p>
    </div>
  )
}

export default App
`,
      })
      files.push({
        path: 'src/index.tsx',
        content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
)
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
`,
      })
    } else {
      files.push({
        path: 'src/index.ts',
        content: `/**
 * ${project.name}
 * ${project.description || ''}
 */

console.log('Hello from ${project.name}!')

// TODO: Implement project logic
`,
      })
    }

    // lib/utils.ts
    files.push({
      path: 'src/lib/utils.ts',
      content: `/**
 * Utility functions for ${project.name}
 */

export function cn(...classes: (string | undefined | null | false)[]) {
  return classes.filter(Boolean).join(' ')
}
`,
    })
  } else if (project.category === 'data') {
    files.push({
      path: 'requirements.txt',
      content: `pandas>=2.0.0
numpy>=1.24.0
matplotlib>=3.7.0
`,
    })
    files.push({
      path: 'src/main.py',
      content: `"""
${project.name}
${project.description || ''}
"""

import pandas as pd

def main():
    print("Hello from ${project.name}!")
    # TODO: Implement data processing logic

if __name__ == "__main__":
    main()
`,
    })
  } else {
    files.push({
      path: 'src/main.py',
      content: `"""
${project.name}
${project.description || ''}
"""

def main():
    print("Hello from ${project.name}!")
    # TODO: Implement project logic

if __name__ == "__main__":
    main()
`,
    })
  }

  // LICENSE
  files.push({
    path: 'LICENSE',
    content: `MIT License

Copyright (c) ${new Date().getFullYear()} ${project.name}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`,
  })

  return files
}

// GET /api/projects/[id]/download - Download project as ZIP
export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params

    const project = await db.project.findUnique({
      where: { id },
      include: {
        files: true,
      },
    })

    if (!project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      )
    }

    // Collect uploaded files from DB
    const uploadedFiles = project.files

    // Generate the project skeleton files
    const generatedFiles = generateProjectFiles(project)

    // Track paths from uploaded files to avoid duplicates with generated files
    const uploadedPaths = new Set(uploadedFiles.map(f => f.path))

    // Filter out generated files that overlap with uploaded files (uploaded takes precedence)
    const uniqueGeneratedFiles = generatedFiles.filter(f => !uploadedPaths.has(f.path))

    // Create archiver ZIP stream
    const archive = new ZipArchive({
      zlib: { level: 9 }, // Best compression
    })

    // Collect errors
    const errors: string[] = []
    archive.on('error', (err) => {
      errors.push(err.message)
    })

    // Add uploaded files to the archive
    for (const file of uploadedFiles) {
      try {
        let buffer: Buffer
        if (file.encoding === 'base64') {
          buffer = Buffer.from(file.content, 'base64')
        } else {
          buffer = Buffer.from(file.content, 'utf-8')
        }
        archive.append(buffer, { name: file.path })
      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Unknown error'
        console.error(`Failed to add uploaded file ${file.path}:`, msg)
        errors.push(`uploaded:${file.path}: ${msg}`)
      }
    }

    // Add generated skeleton files to the archive
    for (const file of uniqueGeneratedFiles) {
      try {
        archive.append(Buffer.from(file.content, 'utf-8'), { name: file.path })
      } catch (err) {
        const msg = err instanceof Error ? err.message : 'Unknown error'
        console.error(`Failed to add generated file ${file.path}:`, msg)
        errors.push(`generated:${file.path}: ${msg}`)
      }
    }

    // Finalize the archive
    archive.finalize()

    // Convert the archive stream to a buffer
    const chunks: Buffer[] = []
    const readable = Readable.from(archive as unknown as Readable)

    for await (const chunk of readable) {
      chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk))
    }

    const zipBuffer = Buffer.concat(chunks)

    // Build response
    const zipFilename = `${project.name.toLowerCase().replace(/[^a-z0-9]/g, '-')}.zip`

    const headers: Record<string, string> = {
      'Content-Type': 'application/zip',
      'Content-Disposition': `attachment; filename="${zipFilename}"`,
      'Content-Length': String(zipBuffer.length),
    }

    return new NextResponse(zipBuffer, { status: 200, headers })
  } catch (error) {
    console.error('Download project ZIP error:', error)
    return NextResponse.json(
      { error: 'Failed to generate project ZIP' },
      { status: 500 }
    )
  }
}
