import { NextRequest, NextResponse } from 'next/server'
import { db } from '@/lib/db'
import { getDefaultUserId } from '@/lib/auth'

interface GitHubFile {
  path: string
  content: string
}

/**
 * Generate project files based on project category, tech stack, and requirements
 */
function generateProjectFiles(project: {
  name: string
  description: string | null
  category: string | null
  techStack: string | null
  requirements: string | null
  notes: string | null
}): GitHubFile[] {
  const files: GitHubFile[] = []
  const techList: string[] = project.techStack ? JSON.parse(project.techStack) : []
  const techLower = techList.map(t => t.toLowerCase())

  // README.md
  const readme = `# ${project.name}

${project.description || 'A project built with AIOS.'}

## About

${project.requirements ? `### Requirements\n${project.requirements}\n` : ''}
${project.notes ? `### Notes\n${project.notes}\n` : ''}

## Tech Stack

${techList.length > 0 ? techList.map(t => `- ${t}`).join('\n') : '- Not specified'}

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Run development server
npm run dev
\`\`\`

## Project Structure

\`\`\`
src/
├── app/          # Application routes and pages
├── components/   # Reusable UI components
├── lib/          # Utility functions and helpers
└── types/        # TypeScript type definitions
\`\`\`

---

*Generated by [AIOS](https://github.com/ai-os) - AI Operating System*
`
  files.push({ path: 'README.md', content: readme })

  // .gitignore
  const gitignore = `# Dependencies
node_modules/
.pnp
.pnp.js

# Testing
coverage/

# Next.js
.next/
out/

# Production
build/
dist/

# Misc
.DS_Store
*.pem
.env
.env.local
.env.development.local
.env.test.local
.env.production.local

# Debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# Vercel
.vercel

# TypeScript
*.tsbuildinfo
next-env.d.ts
`
  files.push({ path: '.gitignore', content: gitignore })

  // package.json (for Web App, API categories)
  const isWebProject = ['web_app', 'api', 'automation', 'mobile', 'desktop'].includes(project.category || '')
  const isAIProject = project.category === 'ai' || techLower.some(t => t.includes('ai') || t.includes('ml') || t.includes('tensor'))

  if (isWebProject || isAIProject || techLower.some(t => ['javascript', 'typescript', 'react', 'next.js', 'node', 'node.js', 'vue', 'angular'].includes(t))) {
    const isNextJs = techLower.some(t => t.includes('next'))
    const isReact = techLower.some(t => t.includes('react'))
    const isVue = techLower.some(t => t.includes('vue'))

    const packageJson = {
      name: project.name.toLowerCase().replace(/[^a-z0-9]/g, '-'),
      version: '0.1.0',
      description: project.description || `AIOS project: ${project.name}`,
      private: true,
      scripts: isNextJs
        ? { dev: 'next dev', build: 'next build', start: 'next start', lint: 'next lint' }
        : isReact
          ? { dev: 'react-scripts start', build: 'react-scripts build', test: 'react-scripts test', eject: 'react-scripts eject' }
          : isVue
            ? { dev: 'vue-cli-service serve', build: 'vue-cli-service build', lint: 'vue-cli-service lint' }
            : { dev: 'node src/index.js', build: 'tsc', start: 'node dist/index.js' },
      dependencies: {},
      devDependencies: {},
    }
    files.push({ path: 'package.json', content: JSON.stringify(packageJson, null, 2) })

    // tsconfig.json
    if (isNextJs || techLower.some(t => t.includes('typescript'))) {
      const tsconfig = {
        compilerOptions: {
          target: 'es5',
          lib: ['dom', 'dom.iterable', 'esnext'],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: 'esnext',
          moduleResolution: 'bundler',
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: 'preserve',
          incremental: true,
          ...(isNextJs ? { plugins: [{ name: 'next' }] } : {}),
          paths: { '@/*': ['./src/*'] },
        },
        include: ['src', ...(isNextJs ? ['.next/types/**/*.ts'] : [])],
        exclude: ['node_modules'],
      }
      files.push({ path: 'tsconfig.json', content: JSON.stringify(tsconfig, null, 2) })
    }

    // src/ structure
    if (isNextJs) {
      files.push({
        path: 'src/app/page.tsx',
        content: `export default function Home() {
  return (
    <main>
      <h1>${project.name}</h1>
      <p>${project.description || 'Welcome to the project.'}</p>
    </main>
  )
}
`,
      })
      files.push({
        path: 'src/app/layout.tsx',
        content: `import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: '${project.name}',
  description: '${project.description || ''}',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`,
      })
      files.push({
        path: 'src/app/globals.css',
        content: `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
      })
    } else if (isReact) {
      files.push({
        path: 'src/App.tsx',
        content: `import React from 'react'

function App() {
  return (
    <div>
      <h1>${project.name}</h1>
      <p>${project.description || 'Welcome to the project.'}</p>
    </div>
  )
}

export default App
`,
      })
      files.push({
        path: 'src/index.tsx',
        content: `import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
)
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
)
`,
      })
    } else {
      // Generic Node.js project
      files.push({
        path: 'src/index.ts',
        content: `/**
 * ${project.name}
 * ${project.description || ''}
 */

console.log('Hello from ${project.name}!')

// TODO: Implement project logic
`,
      })
    }

    // lib/utils.ts
    files.push({
      path: 'src/lib/utils.ts',
      content: `/**
 * Utility functions for ${project.name}
 */

export function cn(...classes: (string | undefined | null | false)[]) {
  return classes.filter(Boolean).join(' ')
}
`,
    })
  } else if (project.category === 'data') {
    // Data project
    files.push({
      path: 'requirements.txt',
      content: `pandas>=2.0.0
numpy>=1.24.0
matplotlib>=3.7.0
`,
    })
    files.push({
      path: 'src/main.py',
      content: `"""
${project.name}
${project.description || ''}
"""

import pandas as pd

def main():
    print("Hello from ${project.name}!")
    # TODO: Implement data processing logic

if __name__ == "__main__":
    main()
`,
    })
  } else {
    // Generic project
    files.push({
      path: 'src/main.py',
      content: `"""
${project.name}
${project.description || ''}
"""

def main():
    print("Hello from ${project.name}!")
    # TODO: Implement project logic

if __name__ == "__main__":
    main()
`,
    })
  }

  // LICENSE
  files.push({
    path: 'LICENSE',
    content: `MIT License

Copyright (c) ${new Date().getFullYear()} ${project.name}

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`,
  })

  return files
}

/**
 * Create a GitHub repository
 */
async function createGitHubRepo(
  token: string,
  repoName: string,
  options: { private?: boolean; description?: string }
) {
  const response = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      name: repoName,
      description: options.description || '',
      private: options.private ?? false,
      auto_init: false, // We'll create files ourselves
    }),
  })

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}))
    // If repo already exists, that's okay - we'll push to it
    if (response.status === 422 && errorData.message?.includes('already exists')) {
      return { alreadyExists: true }
    }
    throw new Error(errorData.message || `Failed to create repository: ${response.status}`)
  }

  const repoData = await response.json()
  return {
    alreadyExists: false,
    fullName: repoData.full_name,
    htmlUrl: repoData.html_url,
    cloneUrl: repoData.clone_url,
    owner: repoData.owner.login,
  }
}

/**
 * Create or update a file in a GitHub repository
 */
async function createFileInRepo(
  token: string,
  owner: string,
  repo: string,
  filePath: string,
  content: string,
  branch: string = 'main'
) {
  const encodedContent = Buffer.from(content).toString('base64')

  // Check if file already exists (to get its SHA for updating)
  const checkResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}?ref=${branch}`,
    {
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github.v3+json',
      },
    }
  )

  let sha: string | undefined
  if (checkResponse.ok) {
    const fileData = await checkResponse.json()
    sha = fileData.sha
  }

  const body: Record<string, unknown> = {
    message: `Add ${filePath}`,
    content: encodedContent,
    branch,
  }

  if (sha) {
    body.sha = sha
  }

  const response = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${filePath}`,
    {
      method: 'PUT',
      headers: {
        Authorization: `Bearer ${token}`,
        Accept: 'application/vnd.github.v3+json',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(body),
    }
  )

  if (!response.ok) {
    const errorData = await response.json().catch(() => ({}))
    throw new Error(errorData.message || `Failed to create file ${filePath}: ${response.status}`)
  }

  return await response.json()
}

// POST /api/github/push - Push a project to GitHub
export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    const { projectId, repoName, private: isPrivate, description } = body

    if (!projectId) {
      return NextResponse.json(
        { error: 'Project ID is required' },
        { status: 400 }
      )
    }

    const userId = await getDefaultUserId()

    // Get GitHub integration
    const integration = await db.integration.findFirst({
      where: {
        userId,
        type: 'github',
        status: 'connected',
      },
    })

    if (!integration || !integration.credentials) {
      return NextResponse.json(
        { error: 'GitHub integration not configured. Please connect your GitHub account first.' },
        { status: 400 }
      )
    }

    // Parse credentials
    let credentials: { token: string; username: string }
    try {
      credentials = JSON.parse(integration.credentials)
    } catch {
      return NextResponse.json(
        { error: 'Invalid GitHub credentials. Please reconfigure the integration.' },
        { status: 400 }
      )
    }

    const { token, username } = credentials

    // Get project details
    const project = await db.project.findFirst({
      where: {
        id: projectId,
        userId,
      },
    })

    if (!project) {
      return NextResponse.json(
        { error: 'Project not found' },
        { status: 404 }
      )
    }

    // Update project status to indicate push is in progress
    await db.project.update({
      where: { id: projectId },
      data: { githubStatus: 'linked' },
    })

    // Determine repository name
    const finalRepoName = repoName || project.name.toLowerCase().replace(/[^a-z0-9._-]/g, '-')
    const finalDescription = description || project.description || ''

    // Step 1: Create the repository
    const repoResult = await createGitHubRepo(token, finalRepoName, {
      private: isPrivate ?? false,
      description: finalDescription,
    })

    let owner = username
    let repoUrl = `https://github.com/${username}/${finalRepoName}`

    if (!repoResult.alreadyExists && 'owner' in repoResult) {
      owner = repoResult.owner
      repoUrl = repoResult.htmlUrl
    }

    // Step 2: Generate project files
    const files = generateProjectFiles(project)

    // Step 3: Push files to GitHub (sequentially to avoid rate limits)
    const pushedFiles: string[] = []
    const errors: string[] = []

    for (const file of files) {
      try {
        await createFileInRepo(token, owner, finalRepoName, file.path, file.content)
        pushedFiles.push(file.path)
      } catch (fileError) {
        const errorMsg = fileError instanceof Error ? fileError.message : 'Unknown error'
        console.error(`Failed to push file ${file.path}:`, errorMsg)
        errors.push(`${file.path}: ${errorMsg}`)
      }
    }

    // Step 4: Update project with GitHub info
    const branch = 'main'
    const now = new Date()

    await db.project.update({
      where: { id: projectId },
      data: {
        githubRepoUrl: repoUrl,
        githubBranch: branch,
        githubStatus: errors.length === files.length ? 'error' : 'pushed',
        githubPushedAt: now,
      },
    })

    // Update integration lastSyncedAt
    await db.integration.update({
      where: { id: integration.id },
      data: { lastSyncedAt: now },
    })

    // Log agent activity
    await db.agentActivity.create({
      data: {
        agentName: 'GitHub Integration',
        agentType: 'system',
        projectId,
        action: `Pushed project "${project.name}" to GitHub at ${repoUrl}`,
        type: 'milestone',
        status: errors.length === files.length ? 'error' : 'completed',
        metadata: JSON.stringify({
          repoUrl,
          repoName: finalRepoName,
          pushedFiles,
          errors,
          fileCount: files.length,
          successCount: pushedFiles.length,
        }),
      },
    })

    return NextResponse.json({
      success: errors.length < files.length,
      repoUrl,
      repoName: finalRepoName,
      owner,
      branch,
      pushedFiles,
      totalFiles: files.length,
      successCount: pushedFiles.length,
      errors: errors.length > 0 ? errors : undefined,
      githubStatus: errors.length === files.length ? 'error' : 'pushed',
    })
  } catch (error) {
    console.error('Push to GitHub error:', error)

    // Try to update project status to error
    try {
      const body = await request.json().catch(() => ({}))
      if (body.projectId) {
        await db.project.update({
          where: { id: body.projectId },
          data: { githubStatus: 'error' },
        })
      }
    } catch {
      // Ignore update errors
    }

    return NextResponse.json(
      {
        error: error instanceof Error ? error.message : 'Failed to push project to GitHub',
      },
      { status: 500 }
    )
  }
}
